# Generated by Django 5.2.6 on 2025-11-17 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0009_userprofile_face_encoding_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='face_encoding_path',
        ),
    ]
