# Generated by Django 5.2.6 on 2025-11-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0010_remove_userprofile_face_encoding_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='vpin',
            field=models.CharField(default='V1', max_length=5),
        ),
    ]
