# Generated by Django 5.2.6 on 2025-11-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0011_medicine_vpin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('low_stock', 'Low Stock'), ('expired', 'Expired Medicine'), ('system_alert', 'System Alert'), ('user_request', 'User Medicine Request'), ('dispense', 'Medicine Dispensed')], max_length=20),
        ),
    ]
